[package]
name = "vsd"
version = "0.1.0"
authors = ["Sebastian Berglönn <sebastianberglonn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.18"
quicli = "0.4.0"